services:
  - type: redis
    name: agu-portal-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    region: frankfurt
    plan: free

  - type: web
    name: agu-portal-hosting
    runtime: node
    env: node
    region: frankfurt
    plan: free
    buildCommand: NODE_ENV=development yarn && yarn build
    startCommand: yarn start
    healthCheckPath: /api/trpc/healthCheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: agu-portal-database
          property: connectionString
      - key: NEXT_PUBLIC_APP_HOSTNAME
        fromService:
          type: web
          name: agu_portal
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: NEXT_PUBLIC_PORT
        fromService:
          type: web
          name: agu_portal
          envVarKey: PORT
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: lightning
          property: connectionString

databases:
  name: agu-portal-database
  region: frankfurt
  plan: free
